/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchroom;
import resultsUI.resultsPanelUI;
/**
 *
 * @author PRANJAL
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    static String Username;
    
    
    public home(String name) {
        this.Username = name;
        initComponents();
        this.setSize(1920,1080);
        this.setResizable(false);    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bckgPanel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        homeTab = new javax.swing.JMenu();
        bookTab = new javax.swing.JMenu();
        persTab = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home_mainPanel.setLayout(null);

        homePanel.setBackground(new java.awt.Color(227, 143, 242));
        homePanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Please click on Search to continue");
        jLabel2.setToolTipText("");
        homePanel.add(jLabel2);
        jLabel2.setBounds(470, 580, 620, 130);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("WELCOME TO OUR");
        jLabel3.setToolTipText("");
        homePanel.add(jLabel3);
        jLabel3.setBounds(50, 40, 650, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("HOTEL ROOM BOOKING");
        jLabel4.setToolTipText("");
        homePanel.add(jLabel4);
        jLabel4.setBounds(180, 150, 600, 130);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("PORTAL");
        jLabel5.setToolTipText("");
        homePanel.add(jLabel5);
        jLabel5.setBounds(330, 270, 470, 130);

        home_mainPanel.add(homePanel);
        homePanel.setBounds(1060, 130, 800, 680);

        bckgPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg5.jpg"))); // NOI18N
        home_mainPanel.add(bckgPanel);
        bckgPanel.setBounds(0, 0, 1920, 960);

        menuBar.setPreferredSize(new java.awt.Dimension(1920, 126));

        homeTab.setText("<html>&emsp;&emsp;&emsp;HOME</html>");
        homeTab.setToolTipText("Homepage");
        homeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeTab.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        homeTab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        homeTab.setPreferredSize(new java.awt.Dimension(384, 24));
        menuBar.add(homeTab);

        bookTab.setText("<html>&emsp;&emsp;&emsp;BOOK</html>");
        bookTab.setToolTipText("Search for hotels");
        bookTab.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bookTab.setPreferredSize(new java.awt.Dimension(384, 24));
        bookTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTabMouseClicked(evt);
            }
        });
        menuBar.add(bookTab);

        persTab.setText("PERSONAL DETAILS");
        persTab.setToolTipText("View your account details");
        persTab.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        persTab.setPreferredSize(new java.awt.Dimension(384, 24));
        persTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persTabMouseClicked(evt);
            }
        });
        menuBar.add(persTab);

        aboutMenu.setText("<html>&emsp;&emsp;DEVELOPERS</html>");
        aboutMenu.setToolTipText("Get to know more about our sites and other services");
        aboutMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        aboutMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        aboutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuMouseClicked(evt);
            }
        });
        menuBar.add(aboutMenu);

        contactMenu.setText("<html>&emsp;CONTACT US</html>");
        contactMenu.setToolTipText("Contact informtation");
        contactMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        contactMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        contactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMenuMouseClicked(evt);
            }
        });
        menuBar.add(contactMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persTabMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new persDetails(Username).setVisible(true);
    }//GEN-LAST:event_persTabMouseClicked

    private void bookTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTabMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new BookFrame(Username).setVisible(true);
    }//GEN-LAST:event_bookTabMouseClicked

    private void aboutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AboutUs(Username).setVisible(true);
    }//GEN-LAST:event_aboutMenuMouseClicked

    private void contactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ContactUs(Username).setVisible(true);
    }//GEN-LAST:event_contactMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JLabel bckgPanel;
    private javax.swing.JMenu bookTab;
    private javax.swing.JMenu contactMenu;
    private javax.swing.JPanel homePanel;
    private javax.swing.JMenu homeTab;
    private javax.swing.JPanel home_mainPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu persTab;
    // End of variables declaration//GEN-END:variables
}
